### PR TITLE
added subject selection to run.py

### PR DESCRIPTION
**Pull request by bendhouseart**
Draft PR in the event you want to format with black, otherwise switch to ready for review and merge.

### CODE REVIEW

**Comment by mnoergaard** [comment]
Can we update this to be more in line with https://github.com/mnoergaard/petprep_hmc ? @bendhouseart

**Comment by bendhouseart** [comment]
> Can we update this to be more in line with https://github.com/mnoergaard/petprep_hmc ? @bendhouseart

- [ ] Add subject exclude option for subject
- [ ] Refactor to use positional arguments for bids_dir, output_dir, and analysis_level
- [ ] Add session selection/exclusion

Okie dokie, will do the above ^^

**Comment by bendhouseart** [comment]
Not quite there, but they are converging; fails at the session exclusion/inclusion.

**Comment by bendhouseart** [comment]
Input option now aligned with petprep_hmc and petdeface.

**Comment by mnoergaard** [comment]
Feel free to merge after resolving the conflicts in run.py

**Pull request merged**
